### ISSUE TITLE
Tracking: Stable Major Release

### ISSUE THREAD

**Issue by realpha** [realpha/eitherway#9]
Tracking Issue for the the issues to be completed for the stable release:

- [ ] #2 Stabilization of Iterator API
- [ ] #3 Complete Test Suite
- [ ] NPM Package Release
- [ ] Inline Documentation
- [ ] README.md API Docs
